apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: golang/go-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "your-database-url"
